<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My Account</name>
   <tag></tag>
   <elementGuidId>db43f4f6-12ca-41f3-ac32-2470ee833f98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.footer > div.links > ul > li.first > a[title=&quot;My Account&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='top']/body/div/div/div[3]/div/div[4]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7bd56ac9-4092-43c5-86af-55082ca40d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://live.techpanda.org/index.php/customer/account/</value>
      <webElementGuid>cddefba9-d361-417d-8813-112b374c0211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>My Account</value>
      <webElementGuid>10f7e4a5-eec5-4416-bae6-091cb5ead579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Account</value>
      <webElementGuid>5f34a910-c3f6-4464-be10-88519e49a5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/body[@class=&quot;cms-index-index cms-home&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;page&quot;]/div[@class=&quot;footer-container&quot;]/div[@class=&quot;footer&quot;]/div[@class=&quot;links&quot;]/ul[1]/li[@class=&quot;first&quot;]/a[1]</value>
      <webElementGuid>e087b7b4-e99a-4cee-aa4b-c8740582f3ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='top']/body/div/div/div[3]/div/div[4]/ul/li/a</value>
      <webElementGuid>4470a2d5-ca88-4935-b5f8-1fb80ac4b62e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'My Account')])[2]</value>
      <webElementGuid>0aaabd70-e935-4f7a-bc2f-ac01a7a00220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[2]/following::a[1]</value>
      <webElementGuid>f2e9711e-f3fe-47a4-8fe4-836c0cfd579e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Search'])[1]/following::a[1]</value>
      <webElementGuid>3d48d0b9-9ad4-41fd-87ff-a6b6f962935c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orders and Returns'])[1]/preceding::a[1]</value>
      <webElementGuid>83bcd698-0c65-4185-8db7-83105928961b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://live.techpanda.org/index.php/customer/account/'])[3]</value>
      <webElementGuid>f8ebde97-d237-4804-be47-683fc0883c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li/a</value>
      <webElementGuid>29fb124d-e4d3-4256-9c92-4c0e5c49649a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://live.techpanda.org/index.php/customer/account/' and @title = 'My Account' and (text() = 'My Account' or . = 'My Account')]</value>
      <webElementGuid>ffc8c17f-72f8-414a-bff0-e4f2bc53b545</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
