<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_This is a required field</name>
   <tag></tag>
   <elementGuidId>467f4df8-c9ab-41c0-8451-9fe7b1263c39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#advice-required-entry-firstname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='advice-required-entry-firstname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>55c4eb39-d767-44d8-968a-ad019194fe17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validation-advice</value>
      <webElementGuid>9963ef67-7c6c-48c4-9053-43b4c07bc3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advice-required-entry-firstname</value>
      <webElementGuid>d9fab5fc-dc0a-46e5-9bd4-b9e26578847e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This is a required field.</value>
      <webElementGuid>7710643b-d69f-4376-a54a-0912646304b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advice-required-entry-firstname&quot;)</value>
      <webElementGuid>114389d5-3537-4b5a-8159-97ef8db759f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='advice-required-entry-firstname']</value>
      <webElementGuid>18ff375d-1048-41f0-884a-4bf4330c33ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-validate']/div/ul/li/div/div/div/div</value>
      <webElementGuid>d9579ec8-ff1a-407a-98b8-d6d0f986e569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[2]</value>
      <webElementGuid>8f468308-7f6d-40e2-b7fb-0dde4c6b2593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Middle Name/Initial'])[1]/preceding::div[1]</value>
      <webElementGuid>632e1c52-a708-4886-a99f-ee40961ce475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This is a required field.']/parent::*</value>
      <webElementGuid>29e022af-c1a7-412e-a61c-24bab0125f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div/div</value>
      <webElementGuid>38ab7e1d-f73b-4223-a920-fa5b680463dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'advice-required-entry-firstname' and (text() = 'This is a required field.' or . = 'This is a required field.')]</value>
      <webElementGuid>ed597112-d511-43b1-9157-1b60e738cc19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
