<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__lastname</name>
   <tag></tag>
   <elementGuidId>76c31ef3-6612-4c06-b96f-f93d3a050c12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lastname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lastname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9839da1a-8274-4243-9479-8d4e89f1c645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>39086bf8-eb6d-4ae5-ac73-b1d9bf67f015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lastname</value>
      <webElementGuid>4be2e55a-0f05-4c65-924f-424f6238ecbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastname</value>
      <webElementGuid>39a2d300-2dbb-4233-91b4-6bebdc801848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>81c962c3-d8c2-4b77-8b6c-ba04403ec94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>b4adb38a-9ba2-4e99-aa04-ec6db94bc318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text required-entry validation-failed</value>
      <webElementGuid>791cb53c-2bf2-4932-b6ae-a06d0a1af064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lastname&quot;)</value>
      <webElementGuid>fca7340f-1591-487d-9ad9-0f042f4a430f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lastname']</value>
      <webElementGuid>2b5b8394-0d05-49d5-93a1-1441488cd621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-validate']/div/ul/li/div/div[3]/div/input</value>
      <webElementGuid>58fe446a-d11b-4e71-97cc-a6d2f3d1ef71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>15b738cb-90c1-4006-8d5d-d7a5ef01502d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lastname' and @name = 'lastname' and @title = 'Last Name']</value>
      <webElementGuid>c71e878f-a8ad-4409-b351-0c00d4595fe0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
