<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Middle NameInitial_middlename</name>
   <tag></tag>
   <elementGuidId>9b710fd0-f425-4e2e-abf5-3565bd0d777e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#middlename</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='middlename']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90a7a1b6-8518-40da-ae35-872e3f468999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d6450a4-16d0-40db-b6f7-566329bd02f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>middlename</value>
      <webElementGuid>01666502-09b8-4d3c-94cd-b6e444986219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>middlename</value>
      <webElementGuid>27190aa1-5d47-4a62-8afb-635800c16daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Middle Name/Initial</value>
      <webElementGuid>e73ef2c8-2077-4514-bc79-debd945eda5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text validation-passed</value>
      <webElementGuid>a742c66c-ad4f-4271-b036-7aa2a2d2078a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;middlename&quot;)</value>
      <webElementGuid>4565c010-ed06-44ff-9eaa-5c1edf24c9ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='middlename']</value>
      <webElementGuid>47c5ad45-b6f0-4462-9425-3117d51797ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-validate']/div/ul/li/div/div[2]/div/input</value>
      <webElementGuid>15378069-404f-4615-8873-fa199e40e4ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>18de5636-5e40-4627-8a2c-b3a7b3e2ea2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'middlename' and @name = 'middlename' and @title = 'Middle Name/Initial']</value>
      <webElementGuid>33577cbf-f2d8-460a-aa6e-df6fbffbb317</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
