<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Checkout</name>
   <tag></tag>
   <elementGuidId>f83cb088-b45e-4885-aeb0-7cbcabd3118c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-cart']/div[3]/div[4]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.button.checkout-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7c513db8-af9b-4933-b063-a489ce808af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Checkout</value>
      <webElementGuid>6f88bb72-89b6-47e8-8f1a-13aa05896c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button checkout-button</value>
      <webElementGuid>02571205-ec80-4763-91d0-512f59808bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://live.techpanda.org/index.php/checkout/onepage/</value>
      <webElementGuid>bcfad4c4-c912-4048-81b3-5c5d08ec9db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Checkout                        </value>
      <webElementGuid>d8837538-1e88-4123-abaf-d5dcde69d272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-cart&quot;)/div[@class=&quot;minicart-wrapper&quot;]/div[@class=&quot;minicart-actions&quot;]/ul[@class=&quot;checkout-types minicart&quot;]/li[1]/a[@class=&quot;button checkout-button&quot;]</value>
      <webElementGuid>9742b6f4-d5eb-4b03-a217-952d5bcdf0f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-cart']/div[3]/div[4]/ul/li/a</value>
      <webElementGuid>41b5a87f-7551-4a88-8a4b-4935e33bc20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Checkout')]</value>
      <webElementGuid>acdc254f-9152-465c-90ad-19eff924dcd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$130.00'])[2]/following::a[1]</value>
      <webElementGuid>655e1f0a-58f7-4d33-9750-467ea927d2a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart Subtotal:'])[1]/following::a[1]</value>
      <webElementGuid>450ef05f-278c-41e8-ba59-e7a80fa3bd34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Shopping Cart'])[1]/preceding::a[1]</value>
      <webElementGuid>5a16e609-eaf6-4c5a-9003-801e63818c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile'])[1]/preceding::a[2]</value>
      <webElementGuid>6c64dc08-7db9-41bd-8854-ddf4d57e044b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Checkout']/parent::*</value>
      <webElementGuid>c8c1aedf-cebb-4a3b-b7c1-b48b254a3f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://live.techpanda.org/index.php/checkout/onepage/']</value>
      <webElementGuid>2bdb5cd5-646e-4ac5-9079-9cb3d3c10f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li/a</value>
      <webElementGuid>114ff4e5-e498-4498-8a93-66f5a86315e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Checkout' and @href = 'http://live.techpanda.org/index.php/checkout/onepage/' and (text() = '
                            Checkout                        ' or . = '
                            Checkout                        ')]</value>
      <webElementGuid>7fd45968-d64d-4b1b-8500-33d8cbf27cc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
