<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My Account</name>
   <tag></tag>
   <elementGuidId>9aef42d7-44f5-4811-9078-84a168a843da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='top']/body/div/div/div[3]/div/div[4]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.footer > div.links > ul > li.first > a[title=&quot;My Account&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1f2dc0b1-194c-46b1-aeb8-5510940349fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://live.techpanda.org/index.php/customer/account/</value>
      <webElementGuid>d66ac8d3-ce0d-45d7-bf9e-5604ad07f2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>My Account</value>
      <webElementGuid>07d264b1-6151-47a3-8aeb-833a6eabc2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Account</value>
      <webElementGuid>5a9014ca-3095-41c1-a122-739b55436015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/body[@class=&quot;cms-index-index cms-home&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;page&quot;]/div[@class=&quot;footer-container&quot;]/div[@class=&quot;footer&quot;]/div[@class=&quot;links&quot;]/ul[1]/li[@class=&quot;first&quot;]/a[1]</value>
      <webElementGuid>6d340880-5cce-4096-9712-044935594e15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='top']/body/div/div/div[3]/div/div[4]/ul/li/a</value>
      <webElementGuid>21ab4821-7201-4e83-a861-271b6e9a1be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'My Account')])[2]</value>
      <webElementGuid>5e7afef7-aa80-4fcd-9994-f6f5be167797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[2]/following::a[1]</value>
      <webElementGuid>88526394-15be-4d96-af82-443645f87b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Search'])[1]/following::a[1]</value>
      <webElementGuid>d1e1c251-e2f8-428d-bc98-f920d40d83ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orders and Returns'])[1]/preceding::a[1]</value>
      <webElementGuid>f1176bbe-9bed-4aed-974a-0e79a663d90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://live.techpanda.org/index.php/customer/account/'])[3]</value>
      <webElementGuid>9c3e5a7e-c064-430d-9713-71b59458ecfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li/a</value>
      <webElementGuid>be90092b-3436-4af4-9a06-001eac32eca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://live.techpanda.org/index.php/customer/account/' and @title = 'My Account' and (text() = 'My Account' or . = 'My Account')]</value>
      <webElementGuid>41aed13f-719f-4ccc-a85e-8fc28be0275d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
