<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__billingpostcode</name>
   <tag></tag>
   <elementGuidId>3bb430b9-ed2d-43c2-a787-dc51003110d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing:postcode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1d7cdb2-6697-47d5-89df-d7ed3e004120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e04eef4-e209-43fe-bf2e-160d9b011313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Zip</value>
      <webElementGuid>e4dc0c02-2f92-4683-b697-ec2876392c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing[postcode]</value>
      <webElementGuid>52057135-8c28-4191-b27a-58334758ad8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing:postcode</value>
      <webElementGuid>69ab8bb3-a2f4-4833-bc3b-68e39b2c1aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text validate-zip-international  required-entry</value>
      <webElementGuid>a622b440-37c3-48b9-80d0-85b8ca1d10f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing:postcode&quot;)</value>
      <webElementGuid>18607317-3233-4c93-a21b-1bff06b2db19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing:postcode']</value>
      <webElementGuid>064be165-ed2f-4e3c-9604-646a244e8eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='billing-new-address-form']/div/ul/li[6]/div/div/input</value>
      <webElementGuid>9a992ac3-b592-42ad-a737-0c734c73bb77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/div/input</value>
      <webElementGuid>291d2577-ec64-49c0-aad3-82377fa36e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @title = 'Zip' and @name = 'billing[postcode]' and @id = 'billing:postcode']</value>
      <webElementGuid>8989d3fe-1a88-4581-b2d8-91c5b24ac378</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
