<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Check  Money order</name>
   <tag></tag>
   <elementGuidId>6c0ee313-e1e2-40c1-ab09-828467a2e01b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//dt[@id='dt_method_checkmo']/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dt_method_checkmo > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>20f6bea1-0514-4dd4-bbfb-dd67e4d46547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>p_method_checkmo</value>
      <webElementGuid>ec270f1f-af84-41aa-bbd4-155417f348fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Check / Money order </value>
      <webElementGuid>79bf3674-9a3b-42c3-b06b-0fe028449dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dt_method_checkmo&quot;)/label[1]</value>
      <webElementGuid>53deff64-7e15-4f61-91e4-841aa7a9f05d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dt[@id='dt_method_checkmo']/label</value>
      <webElementGuid>e9d0ea32-175c-4f6c-9105-414e9130ceba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[21]/following::label[1]</value>
      <webElementGuid>dba4c28e-9821-4362-8a5a-66342c0da8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='«'])[3]/preceding::label[1]</value>
      <webElementGuid>35473d20-0d31-45a2-af77-c33e2993e496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[4]/preceding::label[1]</value>
      <webElementGuid>751746ff-536b-4686-8a4f-85c85c6cd11f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Check / Money order']/parent::*</value>
      <webElementGuid>ada50565-e096-4ec3-8402-cffa8847fc91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dt[2]/label</value>
      <webElementGuid>773843bf-55b1-45e0-8176-c0bb4e779d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Check / Money order ' or . = 'Check / Money order ')]</value>
      <webElementGuid>6d213a50-2fd6-46d7-898f-de5015939bb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
