<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cart</name>
   <tag></tag>
   <elementGuidId>88483250-c199-4a7f-b153-f9be8b2bbc00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/div[2]/div/div/a/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.skip-link.skip-cart > span.label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f801c9a7-cd35-4c59-b9f4-0495cbc6aa32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c24b5643-12d9-4bc6-ab5f-68ac6619496b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cart</value>
      <webElementGuid>42da1359-0b0b-4d16-a626-32814cef46af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;page-header-container&quot;]/div[@class=&quot;skip-links&quot;]/div[@class=&quot;account-cart-wrapper&quot;]/div[@class=&quot;header-minicart&quot;]/a[@class=&quot;skip-link skip-cart&quot;]/span[@class=&quot;label&quot;]</value>
      <webElementGuid>5f53d47e-1cde-46f6-b4a4-ae221012c3a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div[2]/div/div/a/span[2]</value>
      <webElementGuid>6d55006f-75a3-4a12-a3e5-7270dcc8fb24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/following::span[2]</value>
      <webElementGuid>dab2480b-fca2-4696-a19a-3485329eda26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::span[4]</value>
      <webElementGuid>aff2e85a-4357-415f-a438-28d038e4745b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IPhone'])[1]/preceding::span[2]</value>
      <webElementGuid>5a6a721f-0814-446d-878e-8dc1016c7aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cart']/parent::*</value>
      <webElementGuid>0a981942-01a0-42f7-807f-2a7cb6483c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/span[2]</value>
      <webElementGuid>99613d0e-df41-4476-9e21-700afcd434e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Cart' or . = 'Cart')]</value>
      <webElementGuid>60a4790b-3b50-41b3-bc4b-c7178491fa6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
