<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Empty Cart</name>
   <tag></tag>
   <elementGuidId>fb7c20ce-a189-4665-866e-d50797362175</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empty_cart_button > span > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='empty_cart_button']/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5de12b3a-e7f4-4cbe-ba3a-a1fe3e0c2a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Empty Cart</value>
      <webElementGuid>981cea48-62a5-4f44-a070-764280077bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empty_cart_button&quot;)/span[1]/span[1]</value>
      <webElementGuid>368760ac-8d10-40d8-bb85-0efb28a97123</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='empty_cart_button']/span/span</value>
      <webElementGuid>1fdc5659-f303-4b8a-a811-ee6e7ea84c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Shopping Cart'])[1]/following::span[2]</value>
      <webElementGuid>0996aa8e-a996-48a4-8e44-b95b48e534d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Shopping Cart'])[2]/preceding::span[1]</value>
      <webElementGuid>e9d27342-11a0-44d8-8a40-40fe371667ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-or-'])[1]/preceding::span[3]</value>
      <webElementGuid>3b3abc4b-c849-4db5-a78b-a6a6c5adb566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Empty Cart']/parent::*</value>
      <webElementGuid>7513be0a-77af-49a4-96ad-39a032bc1d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span/span</value>
      <webElementGuid>c2cca17d-4cc4-447e-8de8-1485b940e9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Empty Cart' or . = 'Empty Cart')]</value>
      <webElementGuid>3816cc0a-7d81-4011-a5d3-6bfb3a583524</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
