<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Compare Products</name>
   <tag></tag>
   <elementGuidId>e8b7ea1c-8fc5-4190-8c54-6c7d7eb304c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='top']/body/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>5d1ef6dc-4903-4533-bfdb-44e8d5feedba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compare Products</value>
      <webElementGuid>4473edf4-263a-439b-8199-86768cd38865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/body[@class=&quot;page-popup catalog-product-compare-index&quot;]/div[1]/div[@class=&quot;page-title title-buttons&quot;]/h1[1]</value>
      <webElementGuid>107d365e-8de3-4eb1-bedf-7363737dd722</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='top']/body/div/div/h1</value>
      <webElementGuid>c950069b-d40a-48e3-b891-b0a3f5be97cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$500.00'])[1]/preceding::h1[1]</value>
      <webElementGuid>1c88444b-dd69-4f59-b88a-fb04828263a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regular Price:'])[1]/preceding::h1[1]</value>
      <webElementGuid>f2dc3b38-5176-4a8c-b70f-871e955866ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Compare Products']/parent::*</value>
      <webElementGuid>352345d7-453f-4ffe-831f-7c79717dbffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>2afb93e1-0931-43f1-b4f2-c507bf4784e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Compare Products' or . = 'Compare Products')]</value>
      <webElementGuid>825c95be-aadc-4035-9da2-852733c1aad4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
