<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sony Xperia</name>
   <tag></tag>
   <elementGuidId>d6563303-68c6-4f0e-8855-f07fdd2c81d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Sony Xperia&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='top']/body/div/div/div[2]/div/div[2]/div/div[3]/ul/li[3]/div/h2/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5bacac33-0704-4e03-8599-6b36c642939f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://live.techpanda.org/index.php/mobile/sony-xperia.html</value>
      <webElementGuid>b2d43343-e16b-4aeb-987d-af58dedde462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sony Xperia</value>
      <webElementGuid>95ec91fa-943f-4c7f-aefb-9915252e19c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sony Xperia</value>
      <webElementGuid>b7a6bac3-e320-4961-beca-c52b2e886518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/body[@class=&quot;catalog-category-view categorypath-mobile-html category-mobile&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;page&quot;]/div[@class=&quot;main-container col3-layout&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;col-wrapper&quot;]/div[@class=&quot;col-main&quot;]/div[@class=&quot;category-products&quot;]/ul[@class=&quot;products-grid products-grid--max-4-col first last odd&quot;]/li[@class=&quot;item last&quot;]/div[@class=&quot;product-info&quot;]/h2[@class=&quot;product-name&quot;]/a[1]</value>
      <webElementGuid>71ab0abb-ce91-4d80-a589-e49517c1c242</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='top']/body/div/div/div[2]/div/div[2]/div/div[3]/ul/li[3]/div/h2/a</value>
      <webElementGuid>893bf974-6ebf-41b1-8ae7-cc0bb0b60d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sony Xperia')]</value>
      <webElementGuid>c61b5733-8f89-459c-b964-f1cf3f5ac6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Compare'])[2]/following::a[2]</value>
      <webElementGuid>47a723f5-fe85-42b4-8554-ac8c42cd9baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[2]/following::a[3]</value>
      <webElementGuid>b57d8ef9-7548-408f-9408-8ccce9df8cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$100.00'])[1]/preceding::a[1]</value>
      <webElementGuid>0ec40cf7-e6b7-45f8-be42-c9103e5b9cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Cart'])[3]/preceding::a[2]</value>
      <webElementGuid>739d199d-64a1-4220-9795-8f230b7b5865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sony Xperia']/parent::*</value>
      <webElementGuid>1859733b-e40d-4834-80d0-3569e24c499a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://live.techpanda.org/index.php/mobile/sony-xperia.html'])[2]</value>
      <webElementGuid>219a5297-b09d-4afd-bc5f-a3820a458030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/h2/a</value>
      <webElementGuid>4538119b-94d0-42a3-a4f2-163c25acbe0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://live.techpanda.org/index.php/mobile/sony-xperia.html' and @title = 'Sony Xperia' and (text() = 'Sony Xperia' or . = 'Sony Xperia')]</value>
      <webElementGuid>a4cae2a8-504c-44f6-ae70-320d5453ca38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
