<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Update</name>
   <tag></tag>
   <elementGuidId>fc6ae0e1-563a-4938-87d2-305775edbda2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.product-cart-actions > button[name=&quot;update_cart_action&quot;] > span > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='shopping-cart-table']/tbody/tr/td[4]/button/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8494c170-aa4a-4556-8ffe-243c61a69763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update</value>
      <webElementGuid>f98cac70-cfb4-4e2c-9584-5d1eaadfc7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart-table&quot;)/tbody[1]/tr[@class=&quot;first last odd&quot;]/td[@class=&quot;product-cart-actions&quot;]/button[@class=&quot;button btn-update&quot;]/span[1]/span[1]</value>
      <webElementGuid>c67b1758-19df-40d3-81aa-dbb5a0bf257a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='shopping-cart-table']/tbody/tr/td[4]/button/span/span</value>
      <webElementGuid>cc1b6018-e6bd-4f72-b858-3fdad31172d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$100.00'])[3]/following::span[2]</value>
      <webElementGuid>34473d52-3f6b-4a19-8d68-5840ad1ab8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SKU:'])[1]/following::span[4]</value>
      <webElementGuid>344c421f-91a6-414f-a267-99628e8dbaa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/preceding::span[1]</value>
      <webElementGuid>306876dd-2133-4736-b1ed-773d08a1e9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$100.00'])[4]/preceding::span[1]</value>
      <webElementGuid>2da99304-81d9-4184-aad1-b205ef6d345f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Update']/parent::*</value>
      <webElementGuid>55c7bb4e-97ea-42f7-bb48-b0c7e46c3df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/button/span/span</value>
      <webElementGuid>97e381ba-1277-4cce-8da2-e8629fe47409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Update' or . = 'Update')]</value>
      <webElementGuid>e0b2330d-3583-4264-98c9-828edf81133c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
