<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_100.00</name>
   <tag></tag>
   <elementGuidId>8a9128ff-d00d-44e8-9d3e-950bc7db8426</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='product-price-1']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>16ee0ab4-6cbf-40bd-83b8-58e733b71a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>6d720137-cccd-4fb2-a0f7-8924e0b2c5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$100.00</value>
      <webElementGuid>41d2d89f-831f-41f6-89fe-def23413645a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-price-1&quot;)/span[@class=&quot;price&quot;]</value>
      <webElementGuid>07a20235-e129-4f24-8fc5-28f77a11f587</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='product-price-1']/span</value>
      <webElementGuid>bda8fc39-6680-4e90-884e-cb4dd43310f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sony Xperia'])[3]/following::span[2]</value>
      <webElementGuid>6e5384ba-aab9-42b0-bac2-dd800425d69d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Views'])[1]/following::span[3]</value>
      <webElementGuid>113395fb-fee2-4908-854a-50330b77a67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/preceding::span[1]</value>
      <webElementGuid>90493895-e8f4-4b13-863e-1191b6a3ac2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Your Review'])[1]/preceding::span[2]</value>
      <webElementGuid>67a0018b-b00b-43f7-ab71-acfea12d9095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$100.00']/parent::*</value>
      <webElementGuid>4015bbbe-009e-4474-bead-2895fccbd930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/span</value>
      <webElementGuid>5fcb2f6c-b177-4695-b3d5-7d4d2383ba37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$100.00' or . = '$100.00')]</value>
      <webElementGuid>78a3926a-b782-4a8b-bd10-0c6ab2ea1f7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
